name: clean_gen_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  mason: ^0.1.0-dev.55
  yaml: ^3.1.2
  path: ^1.9.0
  recase: ^4.1.0
  dart_style: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  clean_gen: clean_gen
