name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*' # Recommended best practice: publish only on version tags

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get

      - name: Verify publishing eligibility
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish --force
